parameters:
    gamma_customer_review.manager.class: Gamma\CustomerReview\CustomerReviewBundle\Services\CustomerReviewManager

services:
    gamma.customer_review.manager:
        class: %gamma_customer_review.manager.class%
        arguments: [@service_container]
        calls:
            - [setEm, ["@doctrine.orm.entity_manager"]]
    gamma.customer_review.kernel.request.listener:
        class: Gamma\CustomerReview\CustomerReviewBundle\Listener\KernelEvents
        arguments: [@service_container]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest  